name: Deploy to Akash

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jhonny535/akash-web-app
      AKASH_WALLET_NAME: testwallet
      AKASH_WALLET_MNEMONIC: ${{ secrets.AKASH_WALLET_MNEMONIC }}
      AKASH_KEYRING_BACKEND: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image to DockerHub
        run: docker push $IMAGE_NAME

      - name: Install Akash CLI
        run: |
          curl -LO https://github.com/akash-network/node/releases/download/v0.38.2/akash_0.38.2_Linux_amd64.deb
          sudo dpkg -i akash_0.38.2_Linux_amd64.deb
          akash version

      - name: Debug environment variables
        run: |
          echo "AKASH_WALLET_NAME: $AKASH_WALLET_NAME"
          echo "AKASH_KEYRING_BACKEND: $AKASH_KEYRING_BACKEND"
    
      - name: Restore wallet from mnemonic
        run: |
          echo "$AKASH_WALLET_MNEMONIC" | akash keys add "$AKASH_WALLET_NAME" --recover --keyring-backend "$AKASH_KEYRING_BACKEND"
          akash keys list --keyring-backend "$AKASH_KEYRING_BACKEND"

      - name: Validate deploy.yaml
        run: |
          akash tx deployment create deploy.yaml \
            --from testwallet \
            --keyring-backend test \
            --chain-id akashnet-1 \
            --node https://rpc.akashnet.net:443 \
            --dry-run --debug

      - name: Deploy to Akash Network
        run: |
          akash tx deployment create deploy.yaml \
            --from $AKASH_WALLET_NAME \
            --keyring-backend $AKASH_KEYRING_BACKEND \
            --chain-id akashnet-2 \
            --node https://rpc.akash.forbole.com:443 \
            --gas-prices 0.025uakt \
            --gas auto \
            --gas-adjustment 1.5 \
            -y
